//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Transaction
    {
        public long A_TranID { get; set; }
        public long BranchID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string VoucherNumber { get; set; }
        public string Description { get; set; }
        public string CurrencyCode { get; set; }
        public string PartyName { get; set; }
        public string PartyAddress { get; set; }
        public long Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string AuthorizedBy { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
