//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopDBEntities : DbContext
    {
        public ShopDBEntities()
            : base("name=ShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<MasterInventory> MasterInventory { get; set; }
        public virtual DbSet<MasterInventoryLog> MasterInventoryLog { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderLog> OrderLog { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockLog> StockLog { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Enumaration> Enumaration { get; set; }
        public virtual DbSet<GroupProduct> GroupProduct { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<SpecialOffer> SpecialOffer { get; set; }
        public virtual DbSet<SubCategory> SubCategory { get; set; }
        public virtual DbSet<ProductPrice> ProductPrice { get; set; }
        public virtual DbSet<ProductPriceLog> ProductPriceLog { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    }
}
