//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long OrderID { get; set; }
        public string OrderCode { get; set; }
        public string OrderType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string DeliveryDate { get; set; }
        public Nullable<int> DeliverDue { get; set; }
        public Nullable<long> VendorID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> BranchID { get; set; }
        public Nullable<long> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsVatIncluded { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<decimal> TotalVat { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    }
}
