//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public long OrderDetailsID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<long> DiscountType { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<bool> IsVatIncluded { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<decimal> TotalVat { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<long> OrderStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
