//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long PaymentID { get; set; }
        public Nullable<long> PaymentType { get; set; }
        public Nullable<long> PaymentMethod { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<bool> IsDue { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<decimal> ChangeAmount { get; set; }
        public string CardNo { get; set; }
        public string ChqueNo { get; set; }
        public Nullable<bool> IsChequeCleared { get; set; }
        public string CrDr { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
