//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPriceLog
    {
        public long ProductPriceLogID { get; set; }
        public Nullable<long> ProductPriceID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<decimal> UnitPurchasePrice { get; set; }
        public Nullable<bool> PPVatIncluded { get; set; }
        public Nullable<decimal> PPVatPercent { get; set; }
        public Nullable<decimal> PPVat { get; set; }
        public Nullable<decimal> PPOtherCharge { get; set; }
        public Nullable<decimal> TotalPurchasePrice { get; set; }
        public Nullable<decimal> UnitSalesPrice { get; set; }
        public Nullable<bool> SPVatIncluded { get; set; }
        public Nullable<decimal> SPVatPercent { get; set; }
        public Nullable<decimal> SPVat { get; set; }
        public Nullable<decimal> SPOtherCharge { get; set; }
        public Nullable<decimal> TotalSalesPrice { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
