//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialOffer
    {
        public long SpecialOfferID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public string SpecialOfferText { get; set; }
        public Nullable<System.DateTime> OfferStartDate { get; set; }
        public Nullable<System.DateTime> OfferEndDate { get; set; }
        public Nullable<bool> IsDiscount { get; set; }
        public Nullable<long> DiscountType { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public Nullable<bool> IsCashBack { get; set; }
        public Nullable<long> CashBackType { get; set; }
        public Nullable<decimal> CashBackPercent { get; set; }
        public Nullable<decimal> TotalCashBack { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<decimal> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
