//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public long TransactionID { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<long> TransactionType { get; set; }
        public string TransactionCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<long> PaymentType { get; set; }
        public Nullable<long> PaymentMethod { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CrDr { get; set; }
        public string CardNo { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<bool> IsChequeCleared { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Status { get; set; }
    }
}
