//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagement.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsMapper
    {
        public long TMapperID { get; set; }
        public string TransactionType { get; set; }
        public string TransactionName { get; set; }
        public string TypeCode { get; set; }
        public string CrDr { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
    }
}
